name: release

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 12

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}

      # full checkout for semantic-release
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false

      # Cache npm packages.
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installing dependencies
        run: npm install

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
