name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run linters
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Check bundle size
        run: npm run bundlewatch
